parasoft.eula.accepted=true
selenic.license.use_network=true
license.network.use.specified.server=true
selenic.license.network.edition=automation_edition
license.network.url=https://35.91.247.121:8443
license.network.auth.enabled=true
license.network.user=demo
license.network.password=d3mo-user
